<?php

namespace Database\Seeders;

use App\Models\Passage;
use Illuminate\Database\Seeder;

class PassageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $passages = [
            [
                'title' => 'A Day at the Beach',
                'content' => 'The sun was shining brightly as Sarah walked along the sandy beach. She could feel the warm sand between her toes as she made her way toward the water. The waves were gentle and calm, making it perfect for swimming. Sarah had been looking forward to this day for weeks. She brought her favorite book, a towel, and some snacks. As she settled down on her towel, she noticed children building sandcastles nearby. Their laughter filled the air, creating a joyful atmosphere. Sarah opened her book and began reading, but she couldn\'t help but glance up at the beautiful ocean every few minutes. The water was a stunning shade of blue, and seagulls flew overhead. After reading for a while, Sarah decided to take a swim. The water felt refreshing against her skin. She swam out a little way and then floated on her back, looking up at the clear blue sky. When she returned to shore, she felt relaxed and happy. The beach was the perfect place to spend a summer afternoon. As the day came to an end, Sarah packed up her things and headed home, already planning her next visit.',
                'difficultyLevel' => 'Beginner',
                'numberOfWords' => 178
            ],
            [
                'title' => 'The Mystery of the Old Library',
                'content' => 'Emma had always been fascinated by the old library downtown. It was a massive building with tall windows and a grand entrance that seemed to whisper stories of the past. One afternoon, she decided to explore it for the first time. As she pushed open the heavy wooden doors, she was greeted by the rich scent of old books and polished wood. The library was quieter than she expected, with only a few patrons scattered throughout the reading rooms. Emma wandered through the aisles, running her fingers along the spines of countless books. Each shelf seemed to hold a different world, from ancient history to modern fiction. She noticed a section marked "Local History" and felt drawn to it. As she pulled out a thick leather-bound volume, she discovered something unexpected. Tucked between the pages was an old photograph of someone she thought she recognized. The photograph was dated 1925, and written on the back was a mysterious message. Emma felt her curiosity grow as she tried to decipher the faded handwriting. She decided to ask the librarian about the book and its previous owner. The librarian, an elderly woman with kind eyes, seemed intrigued by Emma\'s discovery. Together, they began to unravel the mystery hidden within the library\'s walls.',
                'difficultyLevel' => 'Intermediate',
                'numberOfWords' => 201
            ],
            [
                'title' => 'The Science of Climate Change',
                'content' => 'Climate change represents one of the most pressing challenges facing humanity in the twenty-first century. Scientists have been studying this phenomenon for decades, gathering evidence from various sources including ice core samples, tree rings, and satellite observations. The primary driver of modern climate change is the increased concentration of greenhouse gases in the atmosphere, particularly carbon dioxide, which has risen dramatically since the Industrial Revolution. When fossil fuels are burned for energy, they release carbon dioxide that traps heat in the Earth\'s atmosphere, creating what is known as the greenhouse effect. This warming leads to numerous consequences: melting ice caps, rising sea levels, more frequent extreme weather events, and shifts in ecosystems. Researchers use sophisticated computer models to predict future climate scenarios based on different emission pathways. These models help policymakers understand the potential impacts of various actions and develop strategies to mitigate the effects. International cooperation is essential, as climate change is a global issue that transcends national boundaries. The Paris Agreement, signed by nearly 200 countries, represents a significant step toward coordinated action. However, individual efforts also matter tremendously. Reducing energy consumption, supporting renewable energy sources, and making sustainable lifestyle choices can collectively make a substantial difference. Education and awareness are crucial components of addressing this challenge, as informed citizens are better equipped to support effective policies and make responsible decisions.',
                'difficultyLevel' => 'Proficient',
                'numberOfWords' => 227
            ],
            [
                'title' => 'The Philosophical Implications of Artificial Intelligence',
                'content' => 'The advent of artificial intelligence has precipitated profound philosophical inquiries that challenge our fundamental understanding of consciousness, free will, and the nature of human existence. As computational systems become increasingly sophisticated, capable of performing tasks that were once exclusively human domains, we must confront questions about the essence of intelligence itself. What distinguishes genuine understanding from sophisticated pattern recognition? Can a machine truly possess consciousness, or is it merely simulating cognitive processes? These questions echo ancient philosophical debates about the mind-body problem, but they now manifest in urgent, practical contexts. The development of large language models has demonstrated remarkable capabilities in generating coherent, contextually appropriate text, yet the underlying mechanisms remain somewhat enigmatic. Some researchers argue that these systems exhibit emergent properties that suggest genuine comprehension, while skeptics maintain that they are merely advanced statistical processors lacking true semantic understanding. The ethical dimensions of AI development are equally complex. As we delegate increasingly significant decisions to algorithmic systems, we must grapple with questions of responsibility, bias, and the potential for unintended consequences. The concept of algorithmic fairness becomes particularly challenging when different definitions of fairness may conflict with one another. Moreover, the economic and social implications of widespread AI adoption raise concerns about inequality, employment displacement, and the concentration of power. Philosophical reflection on these issues is not merely academic; it informs the regulatory frameworks and design principles that will shape our technological future.',
                'difficultyLevel' => 'Advanced',
                'numberOfWords' => 256
            ],
            [
                'title' => 'Epistemological Foundations of Quantum Mechanics',
                'content' => 'The epistemological foundations of quantum mechanics present a conundrum that has perplexed physicists and philosophers for nearly a century. Quantum theory, with its probabilistic predictions and observer-dependent phenomena, challenges classical notions of objective reality and determinism. The Copenhagen interpretation, pioneered by Niels Bohr and Werner Heisenberg, posits that quantum systems exist in superpositions of states until measured, at which point the wave function collapses into a definite state. This interpretation raises profound questions about the role of measurement and observation in determining physical reality. Does the act of observation somehow influence the system, or does it merely reveal a pre-existing state? The many-worlds interpretation, proposed by Hugh Everett, offers an alternative framework by suggesting that all possible quantum outcomes actually occur in parallel universes, thereby avoiding the need for wave function collapse. However, this interpretation introduces its own philosophical complexities, including questions about personal identity and the nature of probability. The mathematical formalism of quantum mechanics is remarkably successful in predicting experimental results, yet its ontological implications remain deeply contested. Bell\'s theorem demonstrated that any local hidden variable theory must be inconsistent with quantum mechanical predictions, forcing us to abandon either locality or realism. The experimental violation of Bell inequalities has validated quantum mechanics while simultaneously challenging our intuitive understanding of the physical world. These developments have prompted a re-examination of fundamental assumptions about causality, locality, and the relationship between mathematics and physical reality. Contemporary research in quantum foundations continues to explore these questions through both theoretical analysis and increasingly sophisticated experimental tests.',
                'difficultyLevel' => 'Master',
                'numberOfWords' => 276
            ],
            [
                'title' => 'The Art of Cooking',
                'content' => 'Cooking is both an art and a science that brings people together. When you step into a kitchen, you enter a world of possibilities where simple ingredients can transform into extraordinary meals. The process begins with selecting fresh, quality ingredients. Whether you\'re choosing vegetables at the market or picking out the perfect cut of meat, the quality of your ingredients directly affects the final result. Once you have your ingredients, preparation is key. This means washing vegetables, cutting them into uniform pieces, and measuring out spices and seasonings. Many experienced cooks will tell you that having everything prepared before you start cooking, known as mise en place, makes the entire process smoother. Cooking techniques vary widely, from the gentle heat of simmering to the intense heat of searing. Each method brings out different flavors and textures in your food. For example, roasting vegetables in the oven caramelizes their natural sugars, creating a sweet, rich flavor. Steaming preserves nutrients and creates a delicate texture. Learning to control heat is one of the most important skills in cooking. Too much heat can burn food, while too little heat might leave it undercooked. Timing is equally crucial. Some dishes require patience, like slow-cooked stews that need hours to develop their complex flavors. Others, like stir-fries, come together in minutes. The key is understanding what each dish needs. Seasoning is another critical aspect. Salt enhances flavors, while herbs and spices add complexity. The best cooks know how to balance these elements, tasting as they go and adjusting until everything is just right.',
                'difficultyLevel' => 'Intermediate',
                'numberOfWords' => 250
            ],
            [
                'title' => 'Exploring the Solar System',
                'content' => 'Our solar system is a fascinating collection of planets, moons, asteroids, and comets that orbit around the Sun. At the center of this system is the Sun, a star that provides light and heat to all the planets. The four inner planets—Mercury, Venus, Earth, and Mars—are called terrestrial planets because they have solid, rocky surfaces. Mercury is the closest planet to the Sun and experiences extreme temperature changes. Venus is covered in thick clouds that trap heat, making it the hottest planet. Earth is unique because it has liquid water and supports life. Mars, often called the Red Planet, has fascinated scientists who are searching for signs of past or present life. Beyond Mars lies the asteroid belt, a region filled with rocky objects of various sizes. The outer planets are much larger and are called gas giants. Jupiter is the largest planet and has a Great Red Spot, which is a giant storm that has been raging for hundreds of years. Saturn is famous for its beautiful rings made of ice and rock particles. Uranus and Neptune are ice giants, composed mostly of water, methane, and ammonia. Scientists continue to explore the solar system using telescopes, space probes, and rovers. Each mission brings new discoveries and helps us understand more about our place in the universe.',
                'difficultyLevel' => 'Beginner',
                'numberOfWords' => 195
            ],
            [
                'title' => 'The Renaissance and Its Impact',
                'content' => 'The Renaissance, a period spanning roughly from the fourteenth to the seventeenth century, marked a profound transformation in European culture, art, and intellectual thought. Emerging from the Middle Ages, this era witnessed a renewed interest in classical learning, humanism, and artistic expression. The movement began in Italy, where wealthy patrons supported artists and scholars who sought to revive the knowledge and aesthetic principles of ancient Greece and Rome. Cities like Florence, Venice, and Rome became centers of artistic innovation, where figures such as Leonardo da Vinci, Michelangelo, and Raphael created masterpieces that continue to inspire awe today. The Renaissance was not merely an artistic movement; it represented a fundamental shift in how people viewed themselves and their relationship to the world. Humanism, a philosophical approach that emphasized the value and agency of human beings, challenged the medieval focus on divine authority and otherworldly concerns. This intellectual shift was facilitated by the invention of the printing press, which made books more accessible and allowed ideas to spread rapidly across Europe. Scientific inquiry also flourished during this period, with figures like Copernicus and Galileo challenging established views about the universe. The Renaissance\'s influence extended beyond Europe through exploration and trade, as European powers expanded their reach across the globe. The movement\'s emphasis on individual achievement, empirical observation, and classical learning laid the groundwork for the Scientific Revolution and the Enlightenment that would follow.',
                'difficultyLevel' => 'Proficient',
                'numberOfWords' => 239
            ],
            [
                'title' => 'The Complexity of Neural Networks',
                'content' => 'Neural networks represent a sophisticated computational paradigm inspired by the biological neural networks that constitute animal brains. These artificial systems consist of interconnected nodes, or neurons, organized in layers that process information through weighted connections. The fundamental architecture typically includes an input layer that receives data, one or more hidden layers that perform transformations, and an output layer that produces results. During training, the network adjusts its connection weights through a process called backpropagation, which minimizes the difference between predicted and actual outputs. This learning mechanism allows neural networks to identify complex patterns within data that might be imperceptible to traditional algorithms. Deep learning, a subset of machine learning utilizing networks with multiple hidden layers, has achieved remarkable success in domains such as image recognition, natural language processing, and game playing. However, the opacity of these systems presents significant challenges. The internal representations that neural networks develop are often difficult to interpret, leading to concerns about their reliability and fairness. Researchers are actively developing techniques for explainable AI to address these limitations. Additionally, neural networks require substantial computational resources and large datasets for effective training, which raises questions about accessibility and environmental impact. Despite these challenges, the continued advancement of neural network architectures promises to expand their capabilities and applications across diverse fields.',
                'difficultyLevel' => 'Advanced',
                'numberOfWords' => 234
            ],
            [
                'title' => 'The Morning Routine',
                'content' => 'Every morning, Tom follows the same routine to start his day. He wakes up at six o\'clock when his alarm clock rings. The first thing he does is stretch his arms and take a deep breath. Then he gets out of bed and walks to the bathroom to brush his teeth and wash his face. The cold water helps him feel more awake. After that, he puts on his exercise clothes and goes for a thirty-minute jog around his neighborhood. Running makes him feel energized and ready for the day ahead. When he returns home, he takes a shower and gets dressed for work. Breakfast is important to Tom, so he always makes time for a healthy meal. He usually eats eggs, toast, and fruit, along with a cup of coffee. While he eats, he reads the news on his phone to stay informed about what\'s happening in the world. After breakfast, he packs his lunch and gathers everything he needs for work. By eight o\'clock, he\'s ready to leave the house. Tom believes that having a consistent morning routine helps him feel organized and prepared for whatever challenges the day might bring.',
                'difficultyLevel' => 'Beginner',
                'numberOfWords' => 180
            ]
        ];

        foreach ($passages as $passage) {
            Passage::create($passage);
        }
    }
}

