<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QuestionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = 
        [
            [
                'passage_id' => 1,
                'question' => 'What was the weather like when Sarah walked along the beach?',
                'option1' => 'It was raining heavily.',
                'option2' => 'The sun was shining brightly.',
                'option3' => 'It was cold and windy.',
                'CorrectOption' => 'The sun was shining brightly.',
            ],
            [
                'passage_id' => 1,
                'question' => 'What did Sarah feel between her toes as she walked?',
                'option1' => 'Cold water.',
                'option2' => 'Sharp shells.',
                'option3' => 'Warm sand.',
                'CorrectOption' => 'Warm sand.',
            ],
            [
                'passage_id' => 1,
                'question' => 'What did Sarah notice the children nearby were doing?',
                'option1' => 'Playing volleyball.',
                'option2' => 'Building sandcastles.',
                'option3' => 'Collecting seashells.',
                'CorrectOption' => 'Building sandcastles.',
            ],
            [
                'passage_id' => 1,
                'question' => 'What did Sarah do after reading her book for a while?',
                'option1' => 'She packed up and went home.',
                'option2' => 'She decided to take a swim.',
                'option3' => 'She ate all her snacks.',
                'CorrectOption' => 'She decided to take a swim.',
            ],
            [
                'passage_id' => 1,
                'question' => 'How did the water feel to Sarah when she went for a swim?',
                'option1' => 'Too cold.',
                'option2' => 'Refreshing.',
                'option3' => 'Very warm.',
                'CorrectOption' => 'Refreshing.',
            ],
            [
                'passage_id' => 2,
                'question' => 'What was the first thing Emma noticed when she pushed open the heavy wooden doors of the library?',
                'option1' => 'The grand entrance and tall windows.',
                'option2' => 'The rich scent of old books and polished wood.',
                'option3' => 'The quiet atmosphere and few patrons.',
                'CorrectOption' => 'The rich scent of old books and polished wood.',
            ],
            [
                'passage_id' => 2,
                'question' => 'Which section of the library did Emma feel drawn to?',
                'option1' => 'Ancient History.',
                'option2' => 'Modern Fiction.',
                'option3' => 'Local History.',
                'CorrectOption' => 'Local History.',
            ],
            [
                'passage_id' => 2,
                'question' => 'What unexpected item did Emma discover tucked between the pages of the leather-bound volume?',
                'option1' => 'A mysterious map.',
                'option2' => 'An old photograph.',
                'option3' => 'A handwritten letter.',
                'CorrectOption' => 'An old photograph.',
            ],
            [
                'passage_id' => 2,
                'question' => 'What was written on the back of the discovered item?',
                'option1' => 'The name of the previous owner.',
                'option2' => 'A mysterious message and the date 1925.',
                'option3' => 'A quote from the book.',
                'CorrectOption' => 'A mysterious message and the date 1925.',
            ],
            [
                'passage_id' => 2,
                'question' => 'What action did Emma take after her discovery?',
                'option1' => 'She immediately left the library to research the photo.',
                'option2' => 'She put the photo back and chose a different book.',
                'option3' => 'She decided to ask the librarian about the book and its previous owner.',
                'CorrectOption' => 'She decided to ask the librarian about the book and its previous owner.',
            ],
            [
                'passage_id' => 3,
                'question' => 'The passage implies that the primary difference between historical and modern climate change is the dramatic increase in which atmospheric component since the Industrial Revolution?',
                'option1' => 'Water vapor, a potent greenhouse gas.',
                'option2' => 'Carbon dioxide, primarily from the combustion of fossil fuels.',
                'option3' => 'Methane, a byproduct of industrial agriculture.',
                'CorrectOption' => 'Carbon dioxide, primarily from the combustion of fossil fuels.',
            ],
            [
                'passage_id' => 3,
                'question' => 'Which of the following data sources is NOT explicitly mentioned as evidence gathered by scientists to study climate change?',
                'option1' => 'Ice core samples.',
                'option2' => 'Ocean sediment analysis.',
                'option3' => 'Satellite observations.',
                'CorrectOption' => 'Ocean sediment analysis.',
            ],
            [
                'passage_id' => 3,
                'question' => 'The function of sophisticated computer models in climate research, as described in the text, is primarily to:',
                'option1' => 'Verify the historical accuracy of ice core data.',
                'option2' => 'Predict future climate scenarios based on varying emission pathways.',
                'option3' => 'Quantify the exact contribution of individual nations to global emissions.',
                'CorrectOption' => 'Predict future climate scenarios based on varying emission pathways.',
            ],
            [
                'passage_id' => 3,
                'question' => 'The passage suggests that the effectiveness of the Paris Agreement is limited by the necessity of which additional factor?',
                'option1' => 'The complete cessation of all fossil fuel use globally.',
                'option2' => 'The development of a single, universally accepted climate model.',
                'option3' => 'Individual efforts and informed citizen support for effective policies.',
                'CorrectOption' => 'Individual efforts and informed citizen support for effective policies.',
            ],
            [
                'passage_id' => 3,
                'question' => "The term 'greenhouse effect' is used in the passage to describe the process where carbon dioxide released from burning fossil fuels causes what result?",
                'option1' => 'The depletion of the ozone layer.',
                'option2' => "The trapping of heat in the Earth's atmosphere.",
                'option3' => 'The increase in ocean salinity and acidity.',
                'CorrectOption' => "The trapping of heat in the Earth's atmosphere.",
            ],
            [
                'passage_id' => 4,
                'question' => 'The passage suggests that the philosophical questions raised by AI are essentially modern manifestations of which long-standing debate?',
                'option1' => 'The nature of technological singularity.',
                'option2' => 'The ancient mind-body problem.',
                'option3' => 'The conflict between determinism and free will.',
                'CorrectOption' => 'The ancient mind-body problem.',
            ],
            [
                'passage_id' => 4,
                'question' => "What is the core distinction the passage encourages us to confront regarding AI's capabilities?",
                'option1' => 'The difference between algorithmic processing and computational speed.',
                'option2' => 'The difference between genuine understanding and sophisticated pattern recognition.',
                'option3' => 'The difference between supervised and unsupervised learning models.',
                'CorrectOption' => 'The difference between genuine understanding and sophisticated pattern recognition.',
            ],
            [
                'passage_id' => 4,
                'question' => "The ethical challenge of 'algorithmic fairness' is complicated by which factor, according to the text?",
                'option1' => 'The difficulty in programming subjective human values into a machine.',
                'option2' => 'The potential for different definitions of fairness to be mutually exclusive.',
                'option3' => 'The lack of transparency in proprietary AI algorithms.',
                'CorrectOption' => 'The potential for different definitions of fairness to be mutually exclusive.',
            ],
            [
                'passage_id' => 4,
                'question' => 'Skeptics of large language models (LLMs) are characterized in the passage as maintaining which view?',
                'option1' => 'That LLMs are incapable of generating contextually appropriate text.',
                'option2' => 'That LLMs possess true semantic understanding despite their statistical nature.',
                'option3' => 'That LLMs are merely advanced statistical processors lacking true semantic understanding.',
                'CorrectOption' => 'That LLMs are merely advanced statistical processors lacking true semantic understanding.',
            ],
            [
                'passage_id' => 4,
                'question' => 'The author concludes that philosophical reflection on AI is not merely academic, but crucial for informing which practical outcomes?',
                'option1' => 'The development of new, more powerful computational hardware.',
                'option2' => 'The creation of new philosophical schools of thought.',
                'option3' => 'The regulatory frameworks and design principles that will shape our technological future.',
                'CorrectOption' => 'The regulatory frameworks and design principles that will shape our technological future.',
            ],
            [
                'passage_id' => 5,
                'question' => "The Copenhagen interpretation resolves the quantum conundrum by positing that a quantum system's superposition collapses into a definite state only upon which specific event?",
                'option1' => 'The passage of time, as dictated by the Schrödinger equation.',
                'option2' => 'The act of measurement or observation.',
                'option3' => 'The system reaching absolute zero temperature.',
                'CorrectOption' => 'The act of measurement or observation.',
            ],
            [
                'passage_id' => 5,
                'question' => 'According to the passage, what is the primary philosophical consequence of the Many-Worlds Interpretation (MWI) that distinguishes it from the Copenhagen Interpretation?',
                'option1' => 'It eliminates the need for the concept of wave function collapse.',
                'option2' => 'It provides a deterministic view of quantum mechanics.',
                'option3' => 'It fully reconciles quantum theory with classical mechanics.',
                'CorrectOption' => 'It eliminates the need for the concept of wave function collapse.',
            ],
            [
                'passage_id' => 5,
                'question' => "Bell's theorem and the subsequent experimental violation of Bell inequalities force physicists to abandon which two classical concepts in combination?",
                'option1' => 'Causality and determinism.',
                'option2' => 'Locality and realism.',
                'option3' => 'Probability and objectivity.',
                'CorrectOption' => 'Locality and realism.',
            ],
            [
                'passage_id' => 5,
                'question' => 'The passage highlights that despite the profound ontological debates, the mathematical formalism of quantum mechanics is universally acknowledged for its:',
                'option1' => 'Clarity in defining objective reality.',
                'option2' => 'Success in predicting experimental results.',
                'option3' => 'Intuitive alignment with classical physics.',
                'CorrectOption' => 'Success in predicting experimental results.',
            ],
            [
                'passage_id' => 5,
                'question' => "The epistemological challenge of quantum mechanics is rooted in its departure from classical physics' reliance on which two fundamental concepts?",
                'option1' => 'Probabilistic predictions and the uncertainty principle.',
                'option2' => 'Objective reality and determinism.',
                'option3' => 'Wave-particle duality and quantization.',
                'CorrectOption' => 'Objective reality and determinism.',
            ],
            [
                'passage_id' => 6,
                'question' => 'What French culinary term, mentioned in the passage, refers to the practice of having all ingredients prepared before starting to cook?',
                'option1' => 'Au gratin.',
                'option2' => 'Mise en place.',
                'option3' => 'A la carte.',
                'CorrectOption' => 'Mise en place.',
            ],
            [
                'passage_id' => 6,
                'question' => 'According to the text, what is the direct effect of roasting vegetables in the oven?',
                'option1' => 'It preserves all of their original nutrients.',
                'option2' => 'It causes their natural sugars to caramelize, creating a sweet, rich flavor.',
                'option3' => 'It creates a delicate texture by using gentle heat.',
                'CorrectOption' => 'It causes their natural sugars to caramelize, creating a sweet, rich flavor.',
            ],
            [
                'passage_id' => 6,
                'question' => 'The passage emphasizes that the quality of the final meal is directly affected by what initial step?',
                'option1' => 'The speed at which the dish is cooked.',
                'option2' => 'The selection of fresh, quality ingredients.',
                'option3' => 'The use of intense heat for searing.',
                'CorrectOption' => 'The selection of fresh, quality ingredients.',
            ],
            [
                'passage_id' => 6,
                'question' => 'What is identified as one of the most important skills in cooking, which, if not controlled, can lead to burning or undercooking?',
                'option1' => 'Mastering the art of seasoning.',
                'option2' => 'Controlling the heat.',
                'option3' => 'Perfecting the timing of all dishes.',
                'CorrectOption' => 'Controlling the heat.',
            ],
            [
                'passage_id' => 6,
                'question' => 'The passage suggests that the role of salt in seasoning is primarily to achieve what effect?',
                'option1' => 'To add complexity to the flavor profile.',
                'option2' => 'To enhance existing flavors.',
                'option3' => 'To create a delicate texture.',
                'CorrectOption' => 'To enhance existing flavors.',
            ],
            [
                'passage_id' => 7,
                'question' => 'What is at the center of our solar system that provides light and heat?',
                'option1' => 'The Earth.',
                'option2' => 'The Moon.',
                'option3' => 'The Sun.',
                'CorrectOption' => 'The Sun.',
            ],
            [
                'passage_id' => 7,
                'question' => 'Which planet is unique because it has liquid water and supports life?',
                'option1' => 'Mars.',
                'option2' => 'Earth.',
                'option3' => 'Venus.',
                'CorrectOption' => 'Earth.',
            ],
            [
                'passage_id' => 7,
                'question' => 'What are the four inner planets (Mercury, Venus, Earth, and Mars) called?',
                'option1' => 'Gas giants.',
                'option2' => 'Ice giants.',
                'option3' => 'Terrestrial planets.',
                'CorrectOption' => 'Terrestrial planets.',
            ],
            [
                'passage_id' => 7,
                'question' => 'Which planet is famous for its beautiful rings made of ice and rock particles?',
                'option1' => 'Jupiter.',
                'option2' => 'Saturn.',
                'option3' => 'Uranus.',
                'CorrectOption' => 'Saturn.',
            ],
            [
                'passage_id' => 7,
                'question' => 'What is the name of the region filled with rocky objects that lies beyond Mars?',
                'option1' => 'The Kuiper Belt.',
                'option2' => 'The Asteroid Belt.',
                'option3' => 'The Oort Cloud.',
                'CorrectOption' => 'The Asteroid Belt.',
            ],
            [
                'passage_id' => 8,
                'question' => 'The passage asserts that the Renaissance represented a fundamental shift in worldview by replacing the medieval focus on divine authority with an emphasis on which philosophical approach?',
                'option1' => 'Scholasticism, emphasizing logic and reason.',
                'option2' => 'Humanism, emphasizing the value and agency of human beings.',
                'option3' => 'Empiricism, emphasizing observation and experimentation.',
                'CorrectOption' => 'Humanism, emphasizing the value and agency of human beings.',
            ],
            [
                'passage_id' => 8,
                'question' => 'Which technological development is credited with facilitating the rapid spread of Renaissance intellectual ideas across Europe?',
                'option1' => 'The development of advanced maritime navigation techniques.',
                'option2' => 'The invention of the printing press.',
                'option3' => 'The refinement of oil painting techniques.',
                'CorrectOption' => 'The invention of the printing press.',
            ],
            [
                'passage_id' => 8,
                'question' => 'The Renaissance began in Italy, primarily due to the presence of which key factor?',
                'option1' => 'The establishment of the first modern universities.',
                'option2' => 'The support of wealthy patrons for artists and scholars.',
                'option3' => 'The political unification of the Italian city-states.',
                'CorrectOption' => 'The support of wealthy patrons for artists and scholars.',
            ],
            [
                'passage_id' => 8,
                'question' => "The passage implies that the Renaissance's intellectual legacy directly laid the foundation for which subsequent historical periods?",
                'option1' => 'The Age of Exploration and the Reformation.',
                'option2' => 'The Scientific Revolution and the Enlightenment.',
                'option3' => 'The Industrial Revolution and the Romantic Era.',
                'CorrectOption' => 'The Scientific Revolution and the Enlightenment.',
            ],
            [
                'passage_id' => 8,
                'question' => "The 'renewed interest in classical learning' during the Renaissance primarily involved reviving the knowledge and aesthetic principles of which two ancient civilizations?",
                'option1' => 'Egypt and Mesopotamia.',
                'option2' => 'Greece and Rome.',
                'option3' => 'Persia and India.',
                'CorrectOption' => 'Greece and Rome.',
            ],
            [
                'passage_id' => 9,
                'question' => 'The process by which a neural network adjusts its connection weights to minimize the error between its predicted and actual outputs is specifically identified as:',
                'option1' => 'Forward propagation.',
                'option2' => 'Backpropagation.',
                'option3' => 'Gradient ascent.',
                'CorrectOption' => 'Backpropagation.',
            ],
            [
                'passage_id' => 9,
                'question' => "The passage identifies the 'opacity' of neural networks as a significant challenge, primarily leading to concerns regarding which two factors?",
                'option1' => 'Computational resource usage and dataset size.',
                'option2' => 'Reliability and fairness.',
                'option3' => 'Biological plausibility and architectural complexity.',
                'CorrectOption' => 'Reliability and fairness.',
            ],
            [
                'passage_id' => 9,
                'question' => "What is the defining characteristic that distinguishes 'Deep learning' from general neural networks, according to the text?",
                'option1' => 'Its exclusive use in image recognition and natural language processing.',
                'option2' => 'Its reliance on biological neural network inspiration.',
                'option3' => 'Its utilization of multiple hidden layers.',
                'CorrectOption' => 'Its utilization of multiple hidden layers.',
            ],
            [
                'passage_id' => 9,
                'question' => 'The internal representations developed by neural networks are often difficult to interpret, a problem that researchers are attempting to solve through the development of:',
                'option1' => 'Quantum computing architectures.',
                'option2' => 'Explainable AI (XAI) techniques.',
                'option3' => 'Reinforcement learning algorithms.',
                'CorrectOption' => 'Explainable AI (XAI) techniques.',
            ],
            [
                'passage_id' => 9,
                'question' => 'In the typical architecture of a neural network, which layer is responsible for performing the primary transformations on the input data before the final result is produced?',
                'option1' => 'The input layer.',
                'option2' => 'The hidden layer(s).',
                'option3' => 'The output layer.',
                'CorrectOption' => 'The hidden layer(s).',
            ],
            [
                'passage_id' => 10,
                'question' => "What time does Tom's alarm clock ring every morning?",
                'option1' => "Seven o'clock.",
                'option2' => "Six o'clock.",
                'option3' => "Five-thirty.",
                'CorrectOption' => "Six o'clock.",
            ],
            [
                'passage_id' => 10,
                'question' => "What does Tom do immediately after stretching and taking a deep breath?",
                'option1' => "He goes for a jog.",
                'option2' => "He gets out of bed and walks to the bathroom.",
                'option3' => "He makes breakfast.",
                'CorrectOption' => "He gets out of bed and walks to the bathroom.",
            ],
            [
                'passage_id' => 10,
                'question' => "How long is Tom's jog around his neighborhood?",
                'option1' => "Fifteen minutes.",
                'option2' => "One hour.",
                'option3' => "Thirty minutes.",
                'CorrectOption' => "Thirty minutes.",
            ],
            [
                'passage_id' => 10,
                'question' => "What does Tom do while he eats his breakfast?",
                'option1' => "He watches television.",
                'option2' => "He reads the news on his phone.",
                'option3' => "He talks to his family.",
                'CorrectOption' => "He reads the news on his phone.",
            ],
            [
                'passage_id' => 10,
                'question' => "By what time is Tom ready to leave the house for work?",
                'option1' => "Seven o'clock.",
                'option2' => "Eight o'clock.",
                'option3' => "Nine o'clock.",
                'CorrectOption' => "Eight o'clock.",
            ],

        ];

        foreach ($questions as $question) {

            Question::create($question);
        }
    }
}
